(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> dictionary update sequence element #0 has length 1; 2 is required"
p3
sS'layer'
p4
S'/home/pratyusha/web2py/applications/yorock/controllers/default.py'
p5
sS'code'
p6
S'def index():\n    response.flash = T("FLAT 20% off today")\n    return dict(\'Welcome to Flipkart\')\n\ndef form():\n\treturn dict()\t\n\n\n"""def user():\n    return dict(form=auth())\n\n\n@cache.action()\ndef download():\n    return response.download(request, db)\n\n\ndef call():\n    return service()"""\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/pratyusha/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/pratyusha/web2py/applications/yorock/controllers/default.py", line 21, in <module>\n  File "/home/pratyusha/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/pratyusha/web2py/applications/yorock/controllers/default.py", line 3, in index\n    return dict(\'Welcome to Flipkart\')\nValueError: dictionary update sequence element #0 has length 1; 2 is required\n'
p11
s.